app1/urls.py
from django.urls import path
from app1 import views

app_name = 'app1'

urlpatterns = [
    path('',views.app1,name='app1'),
    path('signup',views.sign_up,name='signup'),
    path('login',views.userlogin,name='login'),
    path('profile',views.profile,name='profile'),
    path('logout',views.userlogout,name='logout'),
    path('changepwd1',views.changepwd1,name='changepwd1'),
    path('changepwd2',views.changepwd2,name='changepwd2'),
    path('userinfo/<int:id>',views.userinfo,name='userinfo'),
]

djauth/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('app1/',include('app1.urls',namespace='app1'))
]

app1/models.py
from django.db import models

# Create your models here.

app1/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django import forms


class SignupForm(UserCreationForm):
    password2 = forms.CharField(label='Re-Type Password',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        labels = {'email':'Email'}

class UpdateUserProfile(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','groups','date_joined','last_login']
        labels = {'email':'Email'}

class UpdateAdminProfile(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = '__all__'
        labels = {'email':'Email'}

app1/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.http import HttpResponse
# from django.contrib.auth.forms import UserCreationForm
from app1.forms import SignupForm,UpdateUserProfile,UpdateAdminProfile
from django.contrib import messages
from django.contrib.auth.forms import (
                    AuthenticationForm,
                    PasswordChangeForm,
                    SetPasswordForm
                    )
from django.contrib.auth import (
                authenticate,
                login,
                logout,
                get_user,
                update_session_auth_hash
                )
from django.contrib.auth.models import User

# Create your views here.form 


def userinfo(request,id):
    if request.user.is_authenticated:
            if request.user.is_superuser == True:
                user = User.objects.get(pk=id)
                form = UpdateUserProfile(instance=user)
                context = {'form':form,'name':request.user.username}
                return render(request,'app1/userinfo.html',context)
            else:
                return HttpResponse("<h1>You can not see others profile</h1>")
    else:
        return HttpResponseRedirect('/app1/login')

def changepwd2(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = SetPasswordForm(user=request.user,data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request,form.user)
                messages.success(request,'Password Changed successfully!!')
                return HttpResponseRedirect('/app1/profile')
        else:
            form = SetPasswordForm(user=request.user)
        context = {'form':form,'name':request.user.username}
        return render(request,'app1/changepwd2.html',context)
    else:
        return HttpResponseRedirect('/app1/login')

def changepwd1(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PasswordChangeForm(user=request.user,data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request,form.user)
                messages.success(request,'Password Changed successfully!!')
                return HttpResponseRedirect('/app1/profile')
        else:
            form = PasswordChangeForm(user=request.user)
        context = {'form':form,'name':request.user.username}
        return render(request,'app1/changepwd1.html',context)
    else:
        return HttpResponseRedirect('/app1/login')

def userlogout(request):
    logout(request)
    return HttpResponseRedirect('/app1/login')

def profile(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            if request.user.is_superuser == True:
                form = UpdateAdminProfile(request.POST,instance=request.user)
                users = User.objects.all()
            else:
                form = UpdateUserProfile(request.POST,instance=request.user)
                users = None
            if form.is_valid():
                form.save()
                messages.success(request,'User Profile Updated')
        else:
            if request.user.is_superuser == True:
                form = UpdateAdminProfile(instance=request.user)
                users = User.objects.all()
            else:
                form = UpdateUserProfile(instance=request.user)
                users = None
        context = {'form':form,
                   'msg':'this is profile page',
                   'name':request.user.username,
                   'users':users}
        return render(request,'app1/profile.html',context)
    else:
        return HttpResponseRedirect('/app1/login')

def userlogin(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request=request,data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                pwd = form.cleaned_data['password']
                user = authenticate(username=uname,password=pwd)
                if user is not None:
                    login(request,user)
                    messages.success(request,'Login Done !!')
                    return HttpResponseRedirect('/app1/profile')
        else:
            form = AuthenticationForm()
        context = {'form':form,'name':request.user.username}
        return render(request,'app1/login.html',context)
    else:
        return HttpResponseRedirect('/app1/profile')

def sign_up(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            form = SignupForm()
            messages.success(request,'Account Created successfully!!')
    else:
        form = SignupForm()
    context = {'form':form}
    return render(request,'app1/signup.html',context)

def index(request):
    context = {'msg':'This is Index Page','name':request.user.username}
    return render(request,'app1/index.html',context)


def app1(request):
    context = {'msg':'This is APP1 Page'}
    return render(request,'app1/index.html',context)

templates/app1/changepwd1.html
{% extends 'base.html' %}
{% block b1 %}
<style>
    .er{
        color:red;
    }
</style>
    {{msg}}
    <form method="post" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="er">{{error}}</p>
            {% endfor %}
        {% endif %}
        {% for field in form %}
            {{field.label_tag}} {{field}} {{field.errors|striptags}} <br><br>
        {% endfor %}
        <input type="submit" value="ChangePwd">
    </form>
    {% for message in messages %}
        <h3>{{message}}</h3>
    {% endfor %}
{% endblock b1 %}

templates/app1/changepwd2.html
{% extends 'base.html' %}
{% block b1 %}
<style>
    .er{
        color:red;
    }
</style>
    {{msg}}
    <form method="post" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="er">{{error}}</p>
            {% endfor %}
        {% endif %}
        {% for field in form %}
            {{field.label_tag}} {{field}} {{field.errors|striptags}} <br><br>
        {% endfor %}
        <input type="submit" value="ChangePwd">
    </form>
    {% for message in messages %}
        <h3>{{message}}</h3>
    {% endfor %}
{% endblock b1 %}

templates/app1/index.html
{% extends 'base.html' %}
{% block b1 %}
    {{msg}}
{% endblock b1 %}

templates/app1/login.html
{% extends 'base.html' %}
{% block b1 %}
<style>
    .er{
        color:red;
    }
</style>
    {{msg}}
    <form method="post" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="er">{{error}}</p>
            {% endfor %}
        {% endif %}
        {% for field in form %}
            {{field.label_tag}} {{field}} {{field.errors|striptags}} <br><br>
        {% endfor %}
        <input type="submit" value="Login">
    </form>
    {% for message in messages %}
        <h3>{{message}}</h3>
    {% endfor %}
{% endblock b1 %}

templates/app1/profile.html
{% extends 'base.html' %}
{% block b1 %}
    <h2>{{msg}}</h2>
    {% if messages %}
        {% for message in messages %}
        <h3>{{message}} {{name}}</h3>
        {% endfor %}
    {% endif %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="er">{{error}}</p>
            {% endfor %}
        {% endif %}
        {% for field in form %}
            {{field.label_tag}} {{field}} {{field.errors|striptags}} <br><br>
        {% endfor %}
        <input type="submit" value="Update">
    </form>
{% endblock b1 %}

templates/app1/signup.html
{% extends 'base.html' %}
{% block b1 %}
<style>
    .er{
        color:red;
    }
</style>
    {{msg}}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="er">{{error}}</p>
            {% endfor %}
        {% endif %}
        {% for field in form %}
            {{field.label_tag}} {{field}} {{field.errors|striptags}} <br><br>
        {% endfor %}
        <input type="submit" value="Submit">
    </form>
    {% for message in messages %}
        <h3>{{message}}</h3>
    {% endfor %}
{% endblock b1 %}

templates/app1/userinfo.html
{% extends 'base.html' %}
{% block b1 %}
    <h2>{{msg}}</h2>
    {% if users != None %}
        <h2>List of Users</h2>
        {% for user in users %}
           <a href="{% url 'app1:userinfo' user.id %}">{{user.username}}</a> <br><br>
        {% endfor %}
    {% endif %}
    {% if messages %}
        {% for message in messages %}
        <h3>{{message}} {{name}}</h3>
        {% endfor %}
    {% endif %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="er">{{error}}</p>
            {% endfor %}
        {% endif %}
        {% for field in form %}
            {{field.label_tag}} {{field}} {{field.errors|striptags}} <br><br>
        {% endfor %}
        <input type="submit" value="Update">
    </form>
{% endblock b1 %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>BASE</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
        <div>
            <div class="header">
                {% if name == "admin" %}
                <a class="active" href="{% url 'index' %}">DJANGO</a>
                <a href="{% url 'index' %}">HOME</a>
                <a href="{% url 'app1:changepwd1' %}">ChangePwd1</a>
                <a href="{% url 'app1:changepwd2' %}">ChangePwd2</a>
                <a href="{% url 'app1:login' %}">Users</a>
                <a href="{% url 'app1:login' %}">Myprofile</a>
                <a class="right" href="{% url 'app1:logout' %}">LOGOUT</a>
                {% elif name %}
                <a class="active" href="{% url 'index' %}">DJANGO</a>
                <a href="{% url 'index' %}">HOME</a>
                <a href="{% url 'app1:changepwd1' %}">ChangePwd1</a>
                <a href="{% url 'app1:changepwd2' %}">ChangePwd2</a>
                <a href="{% url 'app1:login' %}">Myprofile</a>
                <a class="right" href="{% url 'app1:logout' %}">LOGOUT</a>
                {% else %}
                <a class="active" href="{% url 'index' %}">DJANGO</a>
                <a href="{% url 'index' %}">HOME</a>
                <a class="right" href="{% url 'app1:login' %}">LOGIN</a>
                <a class="right" href="{% url 'app1:signup' %}">SIGNUP</a>
                {% endif %}
            </div>
            <div class="c2">
                {% block b1 %}
                {% endblock b1 %}
            </div>
            <div class="footer">
                <h1>Thanks for visiting</h1>
            </div>
        </div>
    </body>
</html>